image: ubuntu:17.10

stages:
  - build

.build_job: &build_def
  script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
        -DBUILD_VC=ON -DBUILD_UMESIMD=ON -DBUILD_TESTING=ON -DBUILD_BENCHMARKS=ON
    - make && make test

gcc:
  stage: build
  <<: *build_def
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y pkg-config python libgd-dev
    - apt-get install -y cmake git g++
  variables:
    CC: gcc
    CXX: g++

clang:
  stage: build
  <<: *build_def
  before_script:
    - apt-get update -y && apt-get upgrade -y
    - apt-get install -y pkg-config python libgd-dev
    - apt-get install -y cmake git clang
  variables:
    CC: clang
    CXX: clang++
